server:
  port: 9000

spring:
  application:
    name: spring-boot-crud-api

  datasource:
    url: jdbc:postgresql://localhost:5432/crud_db
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate.ddl-auto: validate
    properties.hibernate.enable_lazy_load_no_trans: true
    properties.hibernate.format_sql: false
    properties.hibernate.generate_statistics: false
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate.jdbc.batch_size: 20
    properties.hibernate.order_inserts: true
    properties.hibernate.order_updates: true
    properties.hibernate.jdbc.batch_versioned_data: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
